---
- hosts: docker
  become: true
  tasks:
    - name: install docker
      yum:
        name: docker
        state: present
    - name: start and enable docker
      service:
        name: docker
        state: started
        enabled: True
    - name: 'add users to docker group'
      user:
        name: ec2-user
        groups: docker
        append: yes




